### ISSUE TITLE
Is `geocode_bounding_box` used?

### ISSUE THREAD

**Issue by BenSturmfels** [openplans/shareabouts#233]
With `map.geocode_bounding_box` set in the config.yml, I can't seem to see this restriction being passed through in the Mapbox forward or reverse geocoding HTTP requests.

Here's the config:

```
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: true
  geocoding_engine: 'Mapbox'
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [ 140.7688367367,-37.6436829446,153.8689976931,-28.0833334934 ]
```

Forward:
https://api.mapbox.com/geocoding/v5/mapbox.places/london.json?proximity=147.36111%2C-32.61418&access_token=xxx

Reverse:
https://api.mapbox.com/geocoding/v5/mapbox.places/148.25522602515545,-32.04080138010957.json?access_token=xxx
