### ISSUE TITLE
Select dropdown not displayed properly for comments

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts#64]
Adding a select dropdown to the survey form config shows up with all select item options as  "Option option".

e.g. 

```
    - prompt: _(Select demo)
      type: select
      options:
        - label: _(1)
          value: 1
        - label: _(2)
          value: 2
```

Renders as:

![object object](https://f.cloud.github.com/assets/389766/1702576/78d22af0-609a-11e3-8f7f-b59e4a084600.png)
